name: Basic-Schulung
on:
  workflow_dispatch:
  
jobs:
 build:
  name: my-first-action
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2.4.2
    - uses: ./action-a
      with:
        MY_NAME: Ahmed
